### ISSUE TITLE
Can't view Graph type 2 with GOP

### ISSUE THREAD

**Issue by andposteo** [CrypticSignal/bitrate-plotter#1]
Hi, with parameter -g works well but -gop i received next issue:
```
Traceback (most recent call last):
  File "C:\Soft\bitrate-plotter-main\main.py", line 138, in <module>
    gop_end_times, gop_bitrates = get_gop_bitrates(process, number_of_frames, data_output_path)
  File "C:\Soft\bitrate-plotter-main\ffprobe_output_parser.py", line 72, in get_gop_bitrates
    key_frame, pkt_dts_time, pkt_size = line.strip().split(",")
ValueError: not enough values to unpack (expected 3, got 1)
```

**Comment by CrypticSignal** [comment]
Just did some testing and I do not get the same errror. Can you share the full command that you tried and are you trying to analyse a video file? GOP isn't applicable to audio files.
